name: pro1022
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:

  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  gap: ^3.0.1
  freezed_annotation: ^2.4.4
  uuid: ^4.5.1
  provider: ^6.1.2  
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.4.0
  path_provider: ^2.1.5


dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  flutter_launcher_icons: ^0.14.1
  hive_generator: ^2.0.1
 

flutter:

  uses-material-design: true

  assets:
    - lib/core/assets/imgs/
    - lib/core/assets/imgs/foodIcons/
    - lib/core/assets/imgs/ads/
    - lib/core/assets/imgs/story_highlihgt_imgs/
    - lib/core/assets/imgs/clock/
    - lib/core/assets/imgs/logo/
    - lib/_1112/data/data/ottdata.json

flutter_launcher_icons:
  android: "sesac_log"
  ios: true
  image_path: "lib/core/assets/imgs/sesac_logo.png"
  min_sdk_android: 21